export const cloudRegions = [
  {
    id: "aws-ap-tokyo",
    name: "AWS - ap-northeast-1",
    provider: "AWS",
    serverCount: 24,
    avgLatency: 45,
    uptime: 99.99,
    load: 65,
  },
  {
    id: "gcp-asia-southeast",
    name: "GCP - asia-southeast1",
    provider: "GCP",
    serverCount: 18,
    avgLatency: 52,
    uptime: 99.95,
    load: 58,
  },
  {
    id: "azure-east-asia",
    name: "Azure - eastasia",
    provider: "Azure",
    serverCount: 16,
    avgLatency: 48,
    uptime: 99.98,
    load: 72,
  },
  {
    id: "aws-eu-west",
    name: "AWS - eu-west-1",
    provider: "AWS",
    serverCount: 28,
    avgLatency: 185,
    uptime: 99.99,
    load: 45,
  },
  {
    id: "gcp-us-central",
    name: "GCP - us-central1",
    provider: "GCP",
    serverCount: 22,
    avgLatency: 125,
    uptime: 99.96,
    load: 68,
  },
]
